import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const baseWidth = 360;
const scale = width / baseWidth;
const normalize = (size: number) => Math.round(size * scale);

export const employeesStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F0F4F8',
  },
  header: {
    padding: normalize(20),
    paddingTop: height * 0.08,
    backgroundColor: '#1E3A8A',
  },
  title: {
    fontSize: normalize(28),
    fontWeight: 'bold',
    color: '#FFF',
    textAlign: 'right',
  },
  subtitle: {
    fontSize: normalize(14),
    color: '#93C5FD',
    textAlign: 'right',
    marginTop: normalize(5),
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    margin: normalize(20),
    paddingHorizontal: normalize(15),
    borderRadius: normalize(10),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchIcon: {
    marginRight: normalize(10),
  },
  searchInput: {
    flex: 1,
    padding: normalize(12),
    fontSize: normalize(16),
    textAlign: 'right',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10B981',
    marginHorizontal: normalize(20),
    marginBottom: normalize(20),
    padding: normalize(15),
    borderRadius: normalize(10),
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  addButtonText: {
    color: '#FFF',
    fontSize: normalize(16),
    fontWeight: 'bold',
    marginLeft: normalize(8),
  },
  list: {
    paddingHorizontal: normalize(20),
    paddingBottom: normalize(20),
  },
  employeeCard: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    padding: normalize(15),
    marginBottom: normalize(10),
    borderRadius: normalize(10),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  inactiveCard: {
    opacity: 0.6,
    backgroundColor: '#F8FAFC',
  },
  employeeInfo: {
    flex: 1,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(5),
  },
  employeeName: {
    fontSize: normalize(18),
    fontWeight: 'bold',
    color: '#1E293B',
    textAlign: 'right',
  },
  inactiveBadge: {
    backgroundColor: '#FEE2E2',
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(2),
    borderRadius: normalize(4),
    marginRight: normalize(8),
  },
  inactiveBadgeText: {
    fontSize: normalize(12),
    color: '#EF4444',
  },
  employeePhone: {
    fontSize: normalize(14),
    color: '#64748B',
    textAlign: 'right',
  },
  actions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  actionButton: {
    padding: normalize(10),
    marginRight: normalize(8),
    borderRadius: normalize(50),
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  emptyContainer: {
    alignItems: 'center',
    marginTop: normalize(50),
  },
  emptyText: {
    fontSize: normalize(18),
    color: '#94A3B8',
    marginTop: normalize(10),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '90%',
    backgroundColor: '#FFF',
    borderRadius: normalize(20),
    padding: normalize(20),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(20),
  },
  modalTitle: {
    fontSize: normalize(22),
    fontWeight: 'bold',
    color: '#1E293B',
  },
  input: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: normalize(10),
    padding: normalize(15),
    fontSize: normalize(16),
    marginBottom: normalize(15),
    textAlign: 'right',
  },
  activeToggle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(20),
  },
  activeLabel: {
    fontSize: normalize(16),
    color: '#1E293B',
  },
  toggle: {
    width: normalize(50),
    height: normalize(28),
    borderRadius: normalize(14),
    backgroundColor: '#CBD5E1',
    justifyContent: 'center',
    padding: normalize(2),
  },
  toggleActive: {
    backgroundColor: '#10B981',
  },
  toggleThumb: {
    width: normalize(24),
    height: normalize(24),
    borderRadius: normalize(12),
    backgroundColor: '#FFF',
    alignSelf: 'flex-start',
  },
  toggleThumbActive: {
    alignSelf: 'flex-end',
  },
  saveButton: {
    backgroundColor: '#1E3A8A',
    borderRadius: normalize(10),
    padding: normalize(16),
    alignItems: 'center',
    shadowColor: '#1E3A8A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  saveButtonText: {
    color: '#FFF',
    fontSize: normalize(18),
    fontWeight: 'bold',
  },
});